### ISSUE TITLE
开启插件点击后一直卡在无障碍界面

### ISSUE THREAD

**Issue by RidiculousDoge** [Skykai521/DingDongHelper#22]
开启了助手也还是不行？

**Comment by Damondada** [comment]
我也是一样，红米手机...

**Comment by TeqGin** [comment]
我想并不是"卡"在无障碍界面，而是插件只需要获得无障碍权限以后，也就是你开启无障碍以后，再手动打开叮咚买菜的购物车界面就能自动运行了。
他应该是根据页面内容进行判断然后执行点击事件。
